---
- name: A simple playbook that creates a file on hosts
  hosts: all
  gather_facts: false
 
  vars:
    state: present
 
  tasks:
 
  #- name: try an apt install
  #  apt:
  #    name: moon-buggy
  #    state: latest
  #  become: yes
      
  - name: Create a new file
    copy:
      content: "SUCCESS"
      dest: /tmp/newfile.txt
  #  become: yes
